# [Choice] Node.js version
FROM mcr.microsoft.com/devcontainers/typescript-node:24

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends git-crypt

# ARG EXTRA_NODE_VERSION=20
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm use 20"

# [Optional] Uncomment if you want to install more global node packages
# RUN su node -c "npm install -g firebase-tools"